version: '3.8'

services:
    server:
        build: ./server
        ports: 
            - 5000:5000
        extra_hosts:
            - "localhost:192.168.1.4"

    client:
        build: ./client
        ports: 
            - 8080:3000